### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 798: invalid start byte durring exporting the processed dataset

### ISSUE THREAD

**Issue by jamestch** [alibaba/data-juicer#123]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

请教一下各位大佬：对中文jsonl格式的文本进行去重，前面所有的算子都执行成功了，但是在导出数据的数据报错了，如下图所示：
![image](https://github.com/alibaba/data-juicer/assets/6100838/deb1260e-a9b3-47db-92d6-4cb9c7c9c5af)

**Comment by jamestch** [comment]
发现只要使用stopwords_filter这个算子就会出现上述错误，注释掉该算子处理就正常。我的配置文件如下：
# global parameters
project_name: 'hf-data'
dataset_path: '/data-juicer/tch/ty_hf_data/test.jsonl'
export_path: '/data-juicer/outputs/ty-data/test_processed.jsonl'

np: 50
open_tracer: true
text_keys: 'text'
process:
  - chinese_convert_mapper:
      mode: 't2s'
  - clean_email_mapper:
  - clean_html_mapper:
  - clean_ip_mapper:
  - clean_links_mapper:
  - clean_copyright_mapper:
  - expand_macro_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - remove_non_chinese_character_mapper:
      keep_alphabet: true
      keep_number: true
      keep_punc: true
  - remove_specific_chars_mapper:
      chars_to_remove: '◆●■►▼▲▴∆▻▷❖♡□'
  - remove_table_text_mapper:
      min_col: 2
      max_col: 20
  - remove_words_with_incorrect_substrings_mapper:
      lang: zh 
      tokenization: false
      substrings: ['http', 'www', '.com', 'href', '//']
  - whitespace_normalization_mapper:

  # Filter ops
  - alphanumeric_filter:
      tokenization: false
      min_ratio: 0.0
      max_ratio: 0.9
  - average_line_length_filter:
      min_len: 10
      max_len: 10000
  - character_repetition_filter:
      rep_len: 10
      min_ratio: 0.0
      max_ratio: 0.5
  - flagged_words_filter:
      lang: zh
      tokenization: true
      max_ratio: 0.0045
      flagged_words_dir: ./assets
      use_words_aug: true
      words_aug_group_sizes: [2]
      words_aug_join_char: ""
  - language_id_score_filter:
      lang: zh
      min_score: 0.8
  - maximum_line_length_filter:
      min_len: 10
      max_len: 10000
  - perplexity_filter:
      lang: zh
      max_ppl: 2500
  - special_characters_filter:
      min_ratio: 0.0
      max_ratio: 0.25
  
  - stopwords_filter:
      lang: zh
      tokenization: true
      min_ratio: 0.3
      stopwords_dir: ./assets
      use_words_aug: true
      words_aug_group_sizes: [2]
      words_aug_join_char: ""
  
  - text_length_filter:
      min_len: 10
      max_len: 100000
  - words_num_filter:
      lang: zh
      tokenization: true
      min_num: 10
      max_num: 10000
  - word_repetition_filter:
      lang: zh
      tokenization: true
      rep_len: 10 
      min_ratio: 0.0 
      max_ratio: 0.5
  - document_minhash_deduplicator:                          
      tokenization: character                                    
      window_size: 5                                        
      num_permutations: 256                                   
      jaccard_threshold: 0.7                                 
      num_bands: null                                        
      num_rows_per_band: null                                 
      lowercase: true                                         
      ignore_pattern: null

**Comment by HYLcool** [comment]
你好，感谢你的关注与使用~

你说的这个现象还挺奇怪的，因为stopwords_filter本身按理来说并不会改变样本内容🤔

请问你有试过不使用任何算子，也就是配置文件中process:下面为空，然后读入你的数据集后直接导出能否成功吗？这样可以判断一下你的原始数据集中有没有造成导出失败的内容

**Comment by jamestch** [comment]
> 你好，感谢你的关注与使用~
> 
> 你说的这个现象还挺奇怪的，因为stopwords_filter本身按理来说并不会改变样本内容🤔
> 
> 请问你有试过不使用任何算子，也就是配置文件中process:下面为空，然后读入你的数据集后直接导出能否成功吗？这样可以判断一下你的原始数据集中有没有造成导出失败的内容

试了下process为空也会出现同样的问题

**Comment by HYLcool** [comment]
> 试了下process为空也会出现同样的问题

这样的话，很大可能是你输入的原始数据集中包含一些pyarrow导出时无法兼容的内容（如乱码等特殊内容），可能需要你预先check一下数据集来手动剔除这种样本。

如果你的这份数据集不包含隐私以及版权相关的内容，而且你愿意的话，也可以分享给我们，我们可以帮你check这份数据集，邮箱：lielin.hyl@alibaba-inc.com ，或者从我们的[用户钉钉群](https://qr.dingtalk.com/action/joingroup?spm=a2c22.12281976.0.0.7a8253f30mgpjw&code=v1,k1,C0DI7CwRFrg7gJP5aMC95FUmsNuwuKJboT62BqP5DAk=&_dt_no_comment=1&origin=11)中添加群管理员“烈霖”来分享此份数据
