### ISSUE TITLE
停用词的jsonl文件是什么格式？

### ISSUE THREAD

**Issue by pkugyf** [alibaba/data-juicer#124]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

stopwords_filter有个参数是stopwords_dir – The directory storing the stopwords file(s) whose name includes “stopwords” and in json format
但具体是什么样子的json文件呢,key是什么?可以给一个例子吗

**Comment by HYLcool** [comment]
嗨 @pkugyf ，感谢你的关注与使用！

stopwords和flagged words的json文件示例都可以参考[这个](http://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/data_juicer/stopwords.json)，key为语言code，value为该语言对应的词列表

**Comment by HYLcool** [comment]
有不少开源库整理了这些特殊词类，比如我们这里使用的是参考了big-science处理数据时用到的[词表](https://github.com/bigscience-workshop/data-preparation/blob/main/preprocessing/training/01b_oscar_cleaning_and_filtering/stopwords.py)

其他我们已知的一些词表资料你也可以参考：
- https://github.com/6/stopwords-json
- https://github.com/zacanger/profane-words
- https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

更多的其他资料你也可以尝试搜索一下，应该还是有很多的~

**Comment by pkugyf** [comment]
> 有不少开源库整理了这些特殊词类，比如我们这里使用的是参考了big-science处理数据时用到的[词表](https://github.com/bigscience-workshop/data-preparation/blob/main/preprocessing/training/01b_oscar_cleaning_and_filtering/stopwords.py)
> 
> 其他我们已知的一些词表资料你也可以参考：
> 
> * https://github.com/6/stopwords-json
> * https://github.com/zacanger/profane-words
> * https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
> 
> 更多的其他资料你也可以尝试搜索一下，应该还是有很多的~

谢谢，不过我的意思是针对各个算子的说明还不够，哪里还有更详细的文档？我已经看过的有github、论文和python文档和配置文件里的config_all.yaml

**Comment by HYLcool** [comment]
哦哦，如果你想了解每个具体算子的参数含义以及功能，那[API文档](https://alibaba.github.io/data-juicer/)也就是算子的doc string应该是目前最详细的说明了，以及如果你想了解每个算子对数据样本具体会做什么样的处理和清洗，可以参考各个算子对应的[测试样例](https://github.com/alibaba/data-juicer/tree/main/tests/ops)

文档建设方面我们目前还在改进当中，我们后续会考虑制作一个关于算子的更详细、更易读的说明文档或者网页，感谢你的建议与意见~

**Comment by pkugyf** [comment]
> 哦哦，如果你想了解每个具体算子的参数含义以及功能，那[API文档](https://alibaba.github.io/data-juicer/)也就是算子的doc string应该是目前最详细的说明了，以及如果你想了解每个算子对数据样本具体会做什么样的处理和清洗，可以参考各个算子对应的[测试样例](https://github.com/alibaba/data-juicer/tree/main/tests/ops)
> 
> 文档建设方面我们目前还在改进当中，我们后续会考虑制作一个关于算子的更详细、更易读的说明文档或者网页，感谢你的建议与意见~

测试样例是我还没发现的，赞！
期待更详细的文档
