### ISSUE TITLE
[Bug]: 在使用一些过滤符操作的时候，出现了datasets.builder.DatasetGenerationError: An error occurred while generating the dataset报错，想知道原因，谢谢。

### ISSUE THREAD

**Issue by hitszxs** [alibaba/data-juicer#126]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

source

### Data-Juicer Version Data-Juicer版本

v0.1.2

### Python Version Python版本

3.10.11

### Describe the bug 描述这个bug

![截屏2023-12-08 下午4 05 54](https://github.com/alibaba/data-juicer/assets/116297296/525766fb-c7bb-42aa-81bc-52f80f49a238)

![截屏2023-12-08 下午4 06 05](https://github.com/alibaba/data-juicer/assets/116297296/07cff9da-c832-4132-bd8a-399281364ce8)

### To Reproduce 如何复现

只是编辑了analyser.yaml文件，同时，输入数据是一个文件夹（里面包含了json文件以及txt文件和.sh文件）

**Comment by hitszxs** [comment]
原因是OSError: [Errno 28] No space left on device

**Comment by hitszxs** [comment]
但是想知道在使用analyse.py的时候为什么需要generate dataset呢？麻烦了。

**Comment by zhijianma** [comment]
> 但是想知道在使用analyse.py的时候为什么需要generate dataset呢？麻烦了。

您好，感谢使用Data-Juicer。
您提到的generate 是 datasets 库 加载json文件时，将其转为pyarrow时 进行调用的。

**Comment by hitszxs** [comment]
谢谢您的回答，目前出了个新的问题，  File "/opt/conda/lib/python3.10/site-packages/datasets/table.py", line 2248, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
id: string
q_type: string
q_main: string
option_a: string
option_b: string
option_c: string
option_d: string
option_e: string
std_ans: string
answer: string
answer_detail: string
grade: string
major: string
keypoint: string
to
{'id': Value(dtype='string', id=None), 'content': Value(dtype='string', id=None)}
because column names don't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1353, in _write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1889, in _prepare_split_single
    except Exception as e:
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "/mnt/lustre/tangyang2/xieshuo/data-juicer/tools/analyze_data.py", line 13, in <module>
    main()
    └ <function main at 0x7fcb4f58d120>

  File "/mnt/lustre/tangyang2/xieshuo/data-juicer/tools/analyze_data.py", line 9, in main
    analyser.run()
    │        └ <function Analyser.run at 0x7fc9e8167910>
    └ <data_juicer.core.analyser.Analyser object at 0x7fcb4ed76470>

  File "/workspace/data-juicer/data_juicer/core/analyser.py", line 76, in run
    dataset = self.formatter.load_dataset(load_data_np)
              │    │         │            └ 4
              │    │         └ <function MixtureFormatter.load_dataset at 0x7fc9e854f130>
              │    └ <data_juicer.format.mixture_formatter.MixtureFormatter object at 0x7fc9e81e6b60>
              └ <data_juicer.core.analyser.Analyser object at 0x7fcb4ed76470>

  File "/workspace/data-juicer/data_juicer/format/mixture_formatter.py", line 93, in load_dataset
    dataset = formatter.load_dataset(num_proc)
              │         │            └ 4
              │         └ <function LocalFormatter.load_dataset at 0x7fc9e854e9e0>
              └ <data_juicer.format.json_formatter.JsonFormatter object at 0x7fc9e81e4af0>

  File "/workspace/data-juicer/data_juicer/format/formatter.py", line 63, in load_dataset
    datasets = load_dataset(self.type,
               │            │    └ 'json'
               │            └ <data_juicer.format.json_formatter.JsonFormatter object at 0x7fc9e81e4af0>
               └ <function load_dataset at 0x7fc9e854e290>

  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 1791, in load_dataset
    builder_instance.download_and_prepare(
    │                └ <function DatasetBuilder.download_and_prepare at 0x7fc9e86ef250>
    └ <datasets.packaged_modules.json.json.Json object at 0x7fc9c07568f0>
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 891, in download_and_prepare
    self._download_and_prepare(
    │    └ <function DatasetBuilder._download_and_prepare at 0x7fc9e86ef400>
    └ <datasets.packaged_modules.json.json.Json object at 0x7fc9c07568f0>
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 986, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
    │    │              │                  └ {'file_format': 'arrow', 'num_proc': 4}
    │    │              └ SplitGenerator(name='jsonl', gen_kwargs={'files': [<datasets.download.download_manager.FilesIterable object at 0x7fc9c0757910...
    │    └ <function ArrowBasedBuilder._prepare_split at 0x7fc9e86f41f0>
    └ <datasets.packaged_modules.json.json.Json object at 0x7fc9c07568f0>
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1777, in _prepare_split
    for job_id, done, content in iflatmap_unordered(
        │       │     │          └ <function iflatmap_unordered at 0x7fc9f2c955a0>
        │       │     └ (153928564, 268648929048, {'id': Value(dtype='string', id=None), 'content': Value(dtype='string', id=None)}, 533, [208671, 20...
        │       └ True
        └ 3
  File "/opt/conda/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1377, in iflatmap_unordered
    [async_result.get() for async_result in async_results]
                                            └ [<multiprocess.pool.ApplyResult object at 0x7fc9c0557820>, <multiprocess.pool.ApplyResult object at 0x7fc9c058afb0>, <multipr...
  File "/opt/conda/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1377, in <listcomp>
    [async_result.get() for async_result in async_results]
     │            │         └ <multiprocess.pool.ApplyResult object at 0x7fc9c058afb0>
     │            └ <function ApplyResult.get at 0x7fc9f2c8b9a0>
     └ <multiprocess.pool.ApplyResult object at 0x7fc9c058afb0>
  File "/opt/conda/lib/python3.10/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
          │    └ DatasetGenerationError('An error occurred while generating the dataset')
          └ <multiprocess.pool.ApplyResult object at 0x7fc9c058afb0>

datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

似乎是我的数据集的表格不对应。我将formatter中的# datasets = load_dataset(self.type,
        #                         data_files={
        #                             key.strip('.'): self.data_files[key]
        #                             for key in self.data_files
        #                         },
        #                         num_proc=num_proc,
        #                         **self.kwargs)
        改成：
        datasets = load_from_disk(self.type,
                                data_files={
                                    key.strip('.'): self.data_files[key]
                                    for key in self.data_files
                                },
                                num_proc=num_proc,
                                **self.kwargs)会能解决吗？

**Comment by hitszxs** [comment]
<img width="917" alt="截屏2023-12-11 下午4 55 14" src="https://github.com/alibaba/data-juicer/assets/116297296/6d61fb43-831b-4e54-b635-a04a3ac2bba0">
不好意思，这张图更容易看清些

**Comment by zhijianma** [comment]
从提示信息来看，可能是您的数据集中有的条目中存在key (信息中的column_name) 不一致的情况。比如sample1 = {'a': 'here is sample1'},  sample2 = {'b': 2}。

**Comment by hitszxs** [comment]
> 从提示信息来看，可能是您的数据集中有的条目中存在key (信息中的column_name) 不一致的情况。比如sample1 = {'a': 'here is sample1'}, sample2 = {'b': 2}。
好像是这样的，但是这个数据集太大了，我无法更改这个数据集。可以更改load_dataset()吗？
