### ISSUE TITLE
计算中英文PPL使用的语言模型是什么？

### ISSUE THREAD

**Issue by pkugyf** [alibaba/data-juicer#127]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

算子:perplexity_filter
看源码,这个算子用的语言模型是在
https://huggingface.co/edugp/kenlm
下载的,但这个模型的介绍页里只说用wiki之类的数据训练的,没说具体用了哪个模型进行训练,只是说一个用例用了西班牙语的bert模型
所以想问一下,用来计算中文和英文的ppl的模型是什么模型？

**Comment by zhijianma** [comment]
您好，感谢使用Data-Juicer。
主要参考[BigScience](https://github.com/bigscience-workshop/data-preparation/tree/main/preprocessing/training/01b_oscar_cleaning_and_filtering) 处理OSCAR的流程。
