### ISSUE TITLE
去哪儿可以获取到en_core_web_md-3.5.0.zip模型

### ISSUE THREAD

**Issue by ZengJin123** [alibaba/data-juicer#128]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

<img width="1194" alt="image" src="https://github.com/alibaba/data-juicer/assets/93858590/bce31b8e-b840-4f2b-ac49-e9bd4b0c69f1">

**Comment by ZengJin123** [comment]
<img width="1190" alt="image" src="https://github.com/alibaba/data-juicer/assets/93858590/9219feec-6f19-41b0-9467-2008bebd5b14">

**Comment by zhijianma** [comment]
> <img alt="image" width="1190" src="https://private-user-images.githubusercontent.com/93858590/289435035-9219feec-6f19-41b0-9467-2008bebd5b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTY3ODMsIm5iZiI6MTcwMjI5NjQ4MywicGF0aCI6Ii85Mzg1ODU5MC8yODk0MzUwMzUtOTIxOWZlZWMtNmYxOS00MWIwLTk0NjctMjAwOGJlYmQ1YjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNmVjNTgxMmU2ZGVlNTUzOGMxZWZjMmMxMzBkODAxMGYyMWU3M2E0OWQ3OGEyODIzM2FhMGQ1ZDdmMjQwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sL62_7uhMxDaX2qvpBs0O_3p0ll0Mxwq4NtxCeLYYvU">

您好，感谢使用Data-Juicer.
当您使用spacy 的模型，目前支持的语言为en(en_core_web_md-3.5.0),  zh(zh_core_web_md-3.5.0)。 当data-juicer 模型中未发现模型文件时，会自动从oss下载，需要您的电脑可以联网。当然您也可以手动下载，并放置于 缓存目录，如`/root/.cache/data_juicer/models/`。
下载链接：
[zh模型](https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/data_juicer/models/zh_core_web_md-3.5.0.zip)
[en模型](https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/data_juicer/models/en_core_web_md-3.5.0.zip)
