### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZengJin123** [alibaba/data-juicer#130]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubunto

### Installation Method 安装方式

git clone pip

### Data-Juicer Version Data-Juicer版本

最新版本

### Python Version Python版本

3.8.13

### Describe the bug 描述这个bug

安装pip install -e [.tools]是出现
<img width="1128" alt="image" src="https://github.com/alibaba/data-juicer/assets/93858590/0f209de2-ac15-4748-98ac-1b0b71e30eb4">

### To Reproduce 如何复现

pip install -e [.tools]

**Comment by zhijianma** [comment]
您好，感谢使用Data-Juicer。
从您的截图中发现您的python 版本为3.11。  在这个版本下， `longintrepr.h` 文件被移动到了cython 子目录。
建议您可以安装并切到到正确的python3.8的版本。
另外我们后期会发布与python 版本无关的simhash，敬请关注。

**Comment by HYLcool** [comment]
@ZengJin123 你好，目前我们已经发布了python版本兼容性更好的simhash库，名称为`simhash-pybind`，在最新分支中也已经将simhash的依赖修改为了这一个库，请您拉取最新代码再尝试一下，或者在卸载了已安装的simhash-py库后手动安装
```shell
pip uninstall simhash-py
pip install simhash-pybind
```
