### ISSUE TITLE
[Bug]: 使用ray的情况下出现新问题

### ISSUE THREAD

**Issue by ZengJin123** [alibaba/data-juicer#132]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu

### Installation Method 安装方式

git clone pip install 

### Data-Juicer Version Data-Juicer版本

最新

### Python Version Python版本

3.8.13

### Describe the bug 描述这个bug

![image](https://github.com/alibaba/data-juicer/assets/93858590/06083585-4946-4280-a7ed-c1df7dcd87ac)

### To Reproduce 如何复现

<img width="1013" alt="image" src="https://github.com/alibaba/data-juicer/assets/93858590/b4a8b86a-4b03-4c8a-bfcc-9624ab35ce16">

**Comment by zhijianma** [comment]
您好，请问您使用ray 的版本是多少？ 我本地Mac并未复现您遇到的问题(ray == 2.7.1)
