### ISSUE TITLE
基于Ray分布式进行去重何时能支持？

### ISSUE THREAD

**Issue by newlinfeng-coder** [alibaba/data-juicer#133]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

如题，请问juicer何时基于能够基于ray支持去重，这边有相关规划吗？

**Comment by pan-x-c** [comment]
您好，感谢您对 data-jucier 的关注。我们会优先将data-juicer的能力集成到更适合大规模并行的阿里云 PAI 平台上，Ray 分布式去重算子的支持会之后再评估开发。如果需求紧急，也非常欢迎您作为 contributor 提相关 PR~
