### ISSUE TITLE
如何获取因去重被去掉的数据？

### ISSUE THREAD

**Issue by newlinfeng-coder** [alibaba/data-juicer#134]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

在针对一个1.0743G数据进行去重，最终在outputs文件下得到一个0.9815G的去重后数据集文件，请问如何得到因去重被去掉的数据？

**Comment by zhijianma** [comment]
目前暂时的方法为开启tracer 配置，并将其数量设置为一个比较大，比如数据集的一定比例。
我们也正在优化这块，能够将所有过滤和去重的数据都单独保存下来。
