### ISSUE TITLE
指标分析-各个指标的解释

### ISSUE THREAD

**Issue by newlinfeng-coder** [alibaba/data-juicer#135]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

![image](https://github.com/alibaba/data-juicer/assets/28260618/6136aae3-d5fe-4daf-ad87-a692f6ddb882)
请问贵团队，我们在做analysis时，这些指标的解释说明在哪个readme可以找到？有部分指标还不太理解。

本人也对该开源项目十分感兴趣

**Comment by zhijianma** [comment]
您好，感谢您使用Data-Juicer。
我们使用的 `pandas` 库的 **DataFrame** 进行的统计 ，[可参考](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) 。如您截图所示，
-  row1-row3 主要针对非数字类，unique 表示类目数量， top 表示数量最多的类目， freq表示最多的数量。
-  row6-rwo9 主要针对数字类。
-  column 上为您配置中Filter ops的输出指标，基本和op的名称有关联，比如alnum_ratio 表示alphanumeric_filter的输出。目前可以参考 [OPs](https://github.com/alibaba/data-juicer/blob/main/docs/Operators.md) 或者 [算子](https://github.com/alibaba/data-juicer/blob/main/docs/Operators_ZH.md) 。另外我们也在考虑添加有关算子和指标对应关系以及更加详细说明文档，让大家更加容易理解和快速上手。

**Comment by newlinfeng-coder** [comment]
感谢回复，不愧是阿里，回答效率杠杠的，希望项目能早日把多节点并行和中英文处理做好。
