### ISSUE TITLE
[Bug]:我添加了个随机抽样的操作符，并且已经测试成功，但是在配置文件中使用的时候报错如下，是为什么呢？

### ISSUE THREAD

**Issue by hitszxs** [alibaba/data-juicer#138]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

source

### Python Version Python版本

3.9

### Describe the bug 描述这个bug

<img width="903" alt="截屏2023-12-14 下午6 45 04" src="https://github.com/alibaba/data-juicer/assets/116297296/9158252c-308e-432d-879d-cee63deded36">
上述是测试结果输出。
然后在配置文件中如下：
<img width="416" alt="截屏2023-12-14 下午6 45 57" src="https://github.com/alibaba/data-juicer/assets/116297296/649ec6d2-0cdb-446d-a8d6-0c715a86ee69">
显示错误，输出结果为：
<img width="1022" alt="截屏2023-12-14 下午6 46 25" src="https://github.com/alibaba/data-juicer/assets/116297296/e1657b5f-a7d2-49ec-af31-583c91a8337e">

### To Reproduce 如何复现

import sys
import random  # 新添加的模块

from jsonargparse.typing import PositiveFloat  # 修改导入

from data_juicer.utils.availability_utils import AvailabilityChecking
from data_juicer.utils.constant import Fields, StatsKeys
from data_juicer.utils.model_utils import get_model, prepare_model

from ..base_op import OPERATORS, Filter
from ..common import get_words_from_document

@OPERATORS.register_module('random_sample_filter')
class RandomSampleFilter(Filter):
    """Filter to randomly sample a percentage of samples."""

    def __init__(self,
                 tokenization: bool = False,
                 sample_percentage: PositiveFloat = 0.1,  # 修改参数
                 *args,
                 **kwargs):
        """
        Initialization method.

        :param hf_tokenizer: the tokenizer name of Hugging Face tokenizers.
        :param sample_percentage: The percentage of samples to keep.
        :param args: extra args
        :param kwargs: extra args
        """
        super().__init__(*args, **kwargs)
        self.sample_percentage = sample_percentage
        self.model_key = None
        

    def compute_stats(self, sample):
        # 不再计算标记数
        return sample

    def process(self, sample):
        # 根据随机概率决定是否保留样本
        if random.uniform(0, 1) <= self.sample_percentage:
            return True
        else:
            return False
这是我的random_sample_filter.py文件。

**Comment by hitszxs** [comment]
是没有将random_sample_filte检测为op符吗？
麻烦解答了！

**Comment by hitszxs** [comment]
补充一点，这样同样的报相同的错误

<img width="383" alt="截屏2023-12-14 下午6 50 59" src="https://github.com/alibaba/data-juicer/assets/116297296/3ac2b5a1-da86-4821-ae3e-b1bb8c04096c">

**Comment by hitszxs** [comment]
<img width="1012" alt="截屏2023-12-14 下午7 07 39" src="https://github.com/alibaba/data-juicer/assets/116297296/88684dca-1399-4f8e-a551-d7bc2e6fd112">
补充如上。

**Comment by zhijianma** [comment]
您好，请在`data_juicer/ops/filter/__init__.py` import 您的文件

**Comment by hitszxs** [comment]
您好，谢谢您。是的，我操作不当了，写进去后忘了保存了。😭
