### ISSUE TITLE
如何针对对象存储中的数据使用data-juicer？

### ISSUE THREAD

**Issue by hitszxs** [alibaba/data-juicer#141]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

如果数据集放在了桶里面，如何调用data-juicer呢？请问有好的方法或者建议吗？

**Comment by HYLcool** [comment]
你好，感谢你的关注与使用~

目前data-juicer暂时不支持从对象存储中直接读取数据，可能需要你将数据移动到本地硬盘上才可以进行读取与处理。

不过我们之后会考虑将来自对象存储的数据源进行支持，但这可能需要一些时间，希望你可以继续保持关注！

**Comment by hitszxs** [comment]
您好，我自行实现了，如果有需要可以将具体方法分享给你。

**Comment by hitszxs** [comment]
> 你好，感谢你的关注与使用~
> 
> 目前data-juicer暂时不支持从对象存储中直接读取数据，可能需要你将数据移动到本地硬盘上才可以进行读取与处理。
> 
> 不过我们之后会考虑将来自对象存储的数据源进行支持，但这可能需要一些时间，希望你可以继续保持关注！

您好，我自行实现了，如果有需要可以将具体方法分享给你。

**Comment by HYLcool** [comment]
那挺好呀👍🏻如果你已经有比较好的实现方案，欢迎提交PR并成为contributor的一员
