### ISSUE TITLE
开源数据集处理耗时信息

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#148]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

https://github.com/alibaba/data-juicer/blob/main/configs/data_juicer_recipes/README_ZH.md
能否提供开源数据集处理耗时信息，或是对应log文件

**Comment by HYLcool** [comment]
你好，处理耗时信息我们暂时还没有系统完整地收集和整理出来，我们会在之后的文档中逐步添加，感谢提醒~
