### ISSUE TITLE
[Bug]: There no attribute `cfs.dataset_dir` in `format.formatter.py:218`

### ISSUE THREAD

**Issue by sylcjl** [alibaba/data-juicer#155]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

Ubuntu

### Installation Method 安装方式

Docker

### Data-Juicer Version Data-Juicer版本

latest

### Python Version Python版本

3.10

### Describe the bug 描述这个bug

There no attribute `cfs.dataset_dir` in `format.formatter.py:218`.
https://github.com/alibaba/data-juicer/blob/main/data_juicer/format/formatter.py#L218

### To Reproduce 如何复现

Use `data_juicer.format.mixture_formatter.py` with
`cfg.data_path=1 xxxxxxx-1.parquet 1 xxxxxxx-2.parquet`

Error Message:
`data_juicer.format.formatter.py:218`
AttributeError: 'Namespace' object has no attribute 'dataset_dir'

### Configs 配置信息

`cfg.data_path=1 xxxxxxx-1.parquet 1 xxxxxxx-2.parquet`

**Comment by HYLcool** [comment]
你好，这个问题目前已经修复，请你拉取main分支的最新代码再进行尝试~
