### ISSUE TITLE
【算子疑问】保留字母数字比例在指定范围内的样本

### ISSUE THREAD

**Issue by newlinfeng-coder** [alibaba/data-juicer#162]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

【算子疑问】请问对于alphanumeric_filter算子：
- Q1：如果是英文，字母数字的比例在0.516~0.915，中文数据字母和数字的比例特别低可能为0，那这个算子的意义在哪？ 
- Q2：此外英文样本如果是一个完整的陈述话语，字母和数字比例高于0.915，个人认为也是高质量数据，为什么不保留？
- Q3：这里面不同的处理方案，例如reapajama的books保留比例是：0.55~0.854，redpajama-cc-2023-06保留比例是：0.7508~0.8591  # 3sigma，这个是怎样计算的？

必须夸一下，非常nice的一个开源项目，还得是阿里

**Comment by chenhesen** [comment]
您好，感谢提问！
data-juicer致力于提供更丰富的算子以应对不同的数据类型和处理策略，对于某个算子本身是否使用以及算子参数的调整取决于用户对于该数据的理解。alphanumeric_filter通常更适合用于code类型的数据，但由于其功能上的通用性，也可以在自然语言类文本上使用。
Q1&Q2: 对于不同类型样本，需要根据实际情况调整算子参数以满足自己的过滤要求。例如对于英文类型样本，通常需要增大min_ratio和max_ratio（以此过滤掉一些非英文或者特殊字符较多的样本）；对于中文类型样本，通常需要减小min_ratio和max_ratio （以此过滤掉一些非中文或者特殊字符较多的样本）; 对于code类型数据，减小max_ratio有助于过滤掉一些配置文件。
Q3: 我们用data-juicer的分析工具计算数据集的统计分布，然后再用3sigma法则调整算子参数。
