### ISSUE TITLE
tools/postprocess/data_mixture.py无法正确混合数据集

### ISSUE THREAD

**Issue by THUchenzhou** [alibaba/data-juicer#172]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

我有10份json文件，共20GB，有的文件是中文语料，有的是英文语料。
现在我采用data_mixture.py混合这些json文件，设置export_shard_size=1,073,741,824（即1GB），预计将生成20份json文件。
运行后却发现如下情况：
1、生成了209份文件，有的是1.4GB，有的是100多MB，有的是30多MB，不应该是生成20份左右的json文件吗。
2、有的文件全是中文语料，有的文件全是英文语料，正确情况不应该是充分混合了吗。
![image](https://github.com/alibaba/data-juicer/assets/149042593/e86a77aa-289f-4e37-9199-f6be8a855005)

**Comment by zhijianma** [comment]
请参看[#153](https://github.com/alibaba/data-juicer/issues/153)。
我们使用了 datasets 库提供的一种叫做 "sharding" 的方法来将数据集分割成多个较小的子数据集  (shards 数量由export_shard_size 反算的到)， 这种分割是基于样本数量而不是字节大小。
