### ISSUE TITLE
官方文档，源代码编译后。无法使用

### ISSUE THREAD

**Issue by WhyMEliu** [alibaba/data-juicer#179]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

python tools/process_data.py --config configs/demo/process.yaml

ImportError: cannot import name 'num_differing_bits' from 'data_juicer.ops.deduplicator.document_simhash_deduplicator' (/Users/liupeng/Documents/Research/data-juicer/data_juicer/ops/deduplicator/document_simhash_deduplicator.py)

我在document_simhash_deduplicator.py，文件中并没有看到

**Comment by x956** [comment]
我也遇到了相同的问题。。。

**Comment by HYLcool** [comment]
你好，这应该是我们最近添加的一个新算子generate_caption_mapper带来的依赖相关的问题，我们会尽快将其修复！

**Comment by HYLcool** [comment]
嗨 @WhyMEliu @x956

这个问题已在 PR #181 中修复，你们可以拉取main分支最新版本代码再尝试一下，抱歉给你们带来困扰

如还有其他问题，欢迎随时联系我们~
