### ISSUE TITLE
[Suggestion] 为Docker镜像添加JDK运行环境

### ISSUE THREAD

**Issue by liuyanyi** [alibaba/data-juicer#182]
### Search before continuing 先搜索，再继续

- [X] I have searched the Data-Juicer issues and found no similar feature requests. 我已经搜索了 Data-Juicer 的 issue 列表但是没有发现类似的功能需求。

### Description 描述

目前提供的Data-juicer镜像在运行质量分类器的时候会报错，提示找不到JAVA_HOME, 建议在Docker镜像构建时加入JDK，做到开箱即用。

下面是我自己测试用的Dockerfile，以现有的datajuicer为基础镜像，加入了微软的openjdk

```Dockerfile
FROM data-juicer:v0.1.3

WORKDIR /opt
# 下载 jdk
RUN wget https://aka.ms/download-jdk/microsoft-jdk-17.0.9-linux-x64.tar.gz -O jdk.tar.gz && \
    tar -xzf jdk.tar.gz && \
    rm -rf jdk.tar.gz && \
    mv jdk-17.0.9+8 jdk

# 设置环境变量
ENV JAVA_HOME=/opt/jdk

# 设置WORKDIR
WORKDIR /data-juicer
```

### Are you willing to submit a PR for this feature? 您是否乐意为此功能提交一个 PR？

- [ ] Yes I'd like to help by submitting a PR! 是的！我愿意提供帮助并提交一个PR！

**Comment by BiqiangWang** [comment]
确实，docker可以额外提供一个镜像包含jdk。基础镜像可以保留以满足更轻量化的需求

**Comment by HYLcool** [comment]
好建议！👍🏻

我们会尽快增加带有jdk的镜像版本，感谢你提供的可行的解决方案~
