### ISSUE TITLE
使用质量分类器中的predict.py功能时会出现一个文件打断运行。

### ISSUE THREAD

**Issue by zhl98** [alibaba/data-juicer#187]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

我运行的命令是python predict.py  /home/a/zhl/mixture/dj_mixture_challenge/input/alpaca_data.jsonl /home/a/zhl/mixture/dj_mixture_challenge/juicer-data/alpaca_data_score
他会产生多个json文件，请问能把他们合在一起吗？
![image](https://github.com/alibaba/data-juicer/assets/51871747/e84a4a96-f787-4637-a4e9-f06d29d4f299)
而且在运行完的时候会弹出这个窗口，请问这是怎么回事？
![image](https://github.com/alibaba/data-juicer/assets/51871747/36851128-8657-4ee9-8e24-2574a15d2919)

**Comment by HYLcool** [comment]
你好，感谢你对Data-Juicer的关注与使用！

你提到的第一个问题，多个json文件是由于pyspark将数据扩散到多个node上进行并行处理的，所以在保存时，pyspark的接口分别保存了多份文件，不过目前我们没有了解到可以将其保存为一个单独的文件的好的方法，我们建议一个好的暂时的解决方法是得到这些文件后，在结果目录下使用如下命令将其合并为一个文件：
```shell
cat part-*.json > single_res_file.json
```

至于第二个弹出窗口的问题，刚好已经被刚才最新的一个 PR #183 解决了，这个PR已经合并到了main分支中，你可以拉取main分支的最新代码再尝试一下

如还有进一步的问题，可随时联系我们~

**Comment by zhl98** [comment]
好的，非常感谢
