### ISSUE TITLE
streamlit run app.py 会卡在please wait页面

### ISSUE THREAD

**Issue by ZengJin123** [alibaba/data-juicer#20]
在demos所有文件夹下运行streamlit run app.py 都会卡在please wait页面，应该怎么解决？

**Comment by ZengJin123** [comment]
解决了，不使用Safari，用chrome浏览器就行了

**Comment by zhijianma** [comment]
辛苦您提供一下操作系统，浏览器，以及streamlit的版本等信息， 谢谢。
另外，可以使用如下代码，简单测试一下环境问题。
```python
import streamlit as st
st.write('Welcome to Data-Juicer')
```
