### ISSUE TITLE
我写好自己的算子后，添加到ops/filter下，并确保写入了init，以及算子的register。但是在单元测试时，仍然无法找到对应的module

### ISSUE THREAD

**Issue by yhr20000319** [alibaba/data-juicer#209]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

我写好自己的算子后，添加到ops/filter下，并确保写入了init，以及算子的register。但是在测试时，仍然无法找到对应的module
一个更具体的例子， 在tests/ops/filter/test_xxx.py中，
我导入两个包
from data_juicer.ops.filter.face_area_filter import FaceAreaFilter
from data_juicer.ops.filter.retain_substring_filter import RetainSubstringFilter 。
前者为data-juicer中原有的包，可以找到，但是我定义的包却无法被找到，想问可能的解决办法。
Traceback (most recent call last):
  File "/root/autodl-tmp/toolkit/data-juicer/tests/ops/filter/test_retain_substring_filter.py", line 5, in <module>
    from data_juicer.ops.filter.retain_substring_filter import RetainSubstringFilter
ModuleNotFoundError: No module named 'data_juicer.ops.filter.retain_substring_filter'

### Additional 额外信息

已经尝试的方法：
1.文件或目录结构问题：
确保 retain_substring_filter.py 文件确实存在于 data_juicer/ops/filter/ 目录下。
确保 data_juicer/ops/filter/ 目录下有一个 __init__.py 文件，即使它是空的。这个文件告诉 Python 该目录应被视为一个包。
2.Python 路径问题：
import sys  
sys.path.append('/path/to/your/project')
3.安装问题：
如果 data_juicer 是一个第三方库，确保你已经使用 pip 或其他包管理工具正确安装了它。

**Comment by zhijianma** [comment]
您好，请问您的Data-Jucier安装方式或者命令是什么？ 
目前猜测一个可能的原因是您使用了pip 源 安装，导致您新添加的算子无法在python 的路径下找到。
建议您从源码安装，这样您本地编辑或新增的文件就会生效。
```shell
cd <path_to_data_juicer>
pip install -v -e .
```

**Comment by hitszxs** [comment]
如果是按照源安装的话，你改变了ops下的算子时需要将环境中的data-juicer中ops算子也改变才能生效。
