### ISSUE TITLE
Why only keep the most frequently occurring suffix when constructing formatter?

### ISSUE THREAD

**Issue by BlockLiu** [alibaba/data-juicer#212]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

When I read following code from [data_juicer/format/formatter.py](https://github.com/alibaba/data-juicer/blob/main/data_juicer/format/formatter.py), I'm curious why there is a **max** operation?
Doesn't this cause some data loss?

Can someone help me explain this?

```
 # local dataset
    if ext_num:
        formatter_num = {}
        for name, formatter in FORMATTERS.modules.items():
            formatter_num[name] = 0
            for ext in ext_num:
                if ext in formatter.SUFFIXES:
                    formatter_num[name] += ext_num[ext]
        formatter = max(formatter_num, key=lambda x: formatter_num[x]) # why there is a max operation?
        target_suffixes = set(ext_num.keys()).intersection(
            set(FORMATTERS.modules[formatter].SUFFIXES))
        return FORMATTERS.modules[formatter](dataset_path,
                                             text_keys=text_keys,
                                             suffixes=target_suffixes,
                                             add_suffix=add_suffix,
                                             **kwargs)
```

**Comment by yxdyc** [comment]
The `max` function is being used to find the formatter name that is associated with the highest number of matching file extensions, in a pythonic, succinct way. Here's a breakdown of what's happening:

1. ext_num is a dictionary that holds the count of files for each file extension within the given dataset_path. It is populated by iterating over the files found by the find_files_with_suffix function.
2. formatter_num is a dictionary that will hold the count of matching file extensions for each available formatter. It is keyed by formatter names.
3. The loop iterates over each formatter name and its corresponding formatter object in FORMATTERS.modules.items().
4. For each formatter, it goes through the counted file extensions in ext_num and checks if the file extension is supported by the formatter (if ext in formatter.SUFFIXES). If it is, it increments the count for that formatter in formatter_num by the number of files with that extension.
5. After populating formatter_num with the counts, the max operation is used to find the formatter with the maximum count of supported file types. The key argument in the max function is a lambda function that tells max to use the values in formatter_num as the basis for comparison.

What the `max` function is essentially doing is equivalent to the following snippet that returns `max_formatter`:
```
max_value = -1
max_formatter = None
for formatter_name, count in formatter_num.items():
    if count > max_value:
        max_value = count
        max_formatter = formatter_name
```

**Comment by BlockLiu** [comment]
> The `max` function is being used to find the formatter name that is associated with the highest number of matching file extensions, in a pythonic, succinct way. Here's a breakdown of what's happening:
> 
> 1. ext_num is a dictionary that holds the count of files for each file extension within the given dataset_path. It is populated by iterating over the files found by the find_files_with_suffix function.
> 2. formatter_num is a dictionary that will hold the count of matching file extensions for each available formatter. It is keyed by formatter names.
> 3. The loop iterates over each formatter name and its corresponding formatter object in FORMATTERS.modules.items().
> 4. For each formatter, it goes through the counted file extensions in ext_num and checks if the file extension is supported by the formatter (if ext in formatter.SUFFIXES). If it is, it increments the count for that formatter in formatter_num by the number of files with that extension.
> 5. After populating formatter_num with the counts, the max operation is used to find the formatter with the maximum count of supported file types. The key argument in the max function is a lambda function that tells max to use the values in formatter_num as the basis for comparison.
> 
> What the `max` function is essentially doing is equivalent to the following snippet that returns `max_formatter`:
> 
> ```
> max_value = -1
> max_formatter = None
> for formatter_name, count in formatter_num.items():
>     if count > max_value:
>         max_value = count
>         max_formatter = formatter_name
> ```

Thanks for your explaination.

But what confusing me is the step5 in your description
> After populating formatter_num with the counts, the max operation is used to find the formatter with the maximum count of supported file types. 

Supposing there are 5 `.json` files and 2 `.parquet` files under folder `/tmp/example`, so only `json_formatter` will be activated, and the 2 parquet files will not be loaded to dataset.
Is that right?

Hoping for your response :D

**Comment by yxdyc** [comment]
> Thanks for your explaination.
> 
> But what confusing me is the step5 in your description
> 
> > After populating formatter_num with the counts, the max operation is used to find the formatter with the maximum count of supported file types.
> 
> Supposing there are 5 `.json` files and 2 `.parquet` files under folder `/tmp/example`, so only `json_formatter` will be activated, and the 2 parquet files will not be loaded to dataset. Is that right?
> 
> Hoping for your response :D

You're right. In this case, the chosen formatter is the one that can handle the greatest number of files under the dataset path based on their file extensions. This is a heuristic assuming that a dataset typically contains data files of a consistent type; otherwise, it may need to be pre-processed to ensure an aligned meta-format.

Thank you for your question. If this implementation does not meet your requirements, we welcome further suggestions and encourage you to submit a pull request to help us improve it :)
