### ISSUE TITLE
some problems with the quality filtering part on keep ratio

### ISSUE THREAD

**Issue by applewangtao** [alibaba/data-juicer#213]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

I'm checking the quality filtering in Data-juicer, but find that there maybe some problems with the keep ratio part. The keep ratio in the table is only 2%~3% as followings. It's so low, Is it right?

model | keep ratio @ label | keep ratio @ pareto
-- | -- | --
GPT-3 quality classifier (estimated) | - | ~1.3%
gpt3 | 3.22% | 1.41%
chinese | 1.81% | -

**Comment by HYLcool** [comment]
Hi, thanks for your interest!

The keep ratios reported in this table are computed on the CommonCrawl dataset, which is actually a very "dirty" and primitive dataset. They are crawled from the Internet, so most data in it are useless (e.g. error messages, ad., navigation bars, ...). So a low keep ratio is reasonable. (GPT3 only keeps 570GB data from 45TB downloaded data after filtering)

This table mainly shows that the evaluated keep ratios of our reproduced quality classifiers can be almost aligned with the quality classifiers in the GPT-3 paper.

**Comment by applewangtao** [comment]
thank you!
