### ISSUE TITLE
What causes visualization to be blank?

### ISSUE THREAD

**Issue by ifshine** [alibaba/data-juicer#22]
Thanks for your excellent work! Question in title. Here is my result.
![20230918-171819](https://github.com/alibaba/data-juicer/assets/47179231/591cdf4e-57b2-4d83-abf4-3b7105495cac)

**Comment by HYLcool** [comment]
Thanks for your question!

If you conduct the diversity analysis on the default demo dataset, you might need to use a smaller count threshold (e.g. 1 or 2) on the upper right corner because there are only few samples in the demo dataset.

We will set a relatively smaller default value for the count threshold to avoid this misleading result~

Please help to handle this question, thanks~ @zhijianma

**Comment by ifshine** [comment]
Thank you for your quick response!

I use my own data(221 examples) and a smaller count threshold(3) really solves the problem.

However, for the default demo dataset,  a smaller count threshold(1) brings no change.

I still do not understand the reason. Can you explain it?

**Comment by HYLcool** [comment]
Umm... That's weird. I tried several times and got the same result as below. Maybe you can restart the app and try again.

<img width="1307" alt="image" src="https://github.com/alibaba/data-juicer/assets/12782861/e2540ac7-d1a1-4f74-a008-5a7c2f0bc23e">

The diversity analysis is mostly for post-tuning data. It analyzes the verb-noun diversity of given samples and clusters them by the verb-noun categories. Only those clusters with a number of samples ≥ count threshold will be kept in the final analysis result. Thus count threshold is set to 1 means all samples that contain any verb-noun phrases will be kept.

BTW, the default value is set to 0 in the latest PR. You can also try to pull the latest code and try again~

**Comment by ifshine** [comment]
😃Thank you for your explanation. I have learned a lot from it.

**Comment by zhijianma** [comment]
![image](https://github.com/alibaba/data-juicer/assets/30956532/b11ae2f7-a90c-46f1-a772-925e6bde4d2a)

**Comment by ifshine** [comment]
I redo the following commands:

git clone -n https://github.com/alibaba/data-juicer
cd data-juicer/
git checkout e221d06f3b8df2ee3dd3c8e76de2e03331817d4d

The visualization of diversity can run correctly(for both the dafault demo dataset and my own data).

**Comment by HYLcool** [comment]
Sorry for this problem. That's because there are some conflicts between `wget` and `streamlit`, which is brought in the last few PRs 😅

We have restored these modifications in the latest PR #24 and merged it into the main branch. You can pull and try again now. Thanks for your report!

**Comment by ifshine** [comment]
It works now lol!
