### ISSUE TITLE
wechat 二维码过期了

### ISSUE THREAD

**Issue by fyubang** [alibaba/data-juicer#225]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

wechat 二维码过期了

### Additional 额外信息

wechat 二维码过期了

**Comment by yxdyc** [comment]
多谢反馈，目前已经更新为有效二维码
