### ISSUE TITLE
读取txt文档时，可以设置成每个\n读取为一条数据吗？

### ISSUE THREAD

**Issue by 1006076811** [alibaba/data-juicer#27]
读取txt文档时，可以设置成每个\n读取为一条数据吗？如何设置？

**Comment by HYLcool** [comment]
您好，目前这个参数暂未暴露到顶层config文件层面，如您需要修改，可将此处的sample_by参数由document改为line
https://github.com/alibaba/data-juicer/blob/34996a0032fc4971a9805250f11efe9d3d2b8a58/data_juicer/format/text_formatter.py#L146

**Comment by 1006076811** [comment]
> 您好，目前这个参数暂未暴露到顶层config文件层面，如您需要修改，可将此处的sample_by参数由document改为line
> 
> https://github.com/alibaba/data-juicer/blob/34996a0032fc4971a9805250f11efe9d3d2b8a58/data_juicer/format/text_formatter.py#L146

感谢您的回答

**Comment by cheramvb** [comment]
你好我加载txt 遇到如下问题 /data-juicer/data_juicer/format/text_formatter.py:194 in load_dataset

    191 │   #             self.data_files[file_type] = find_files_with_suffix(extracte
    192 │   #     safe_kwargs = {k: v for k, v in self.kwargs.items() if k != "num_pro
    193 │   #     # load text dataset, one text file as one sample
  ❱ 194 │   #     datasets = load_dataset(
    195 │   #         "text",
    196 │   #         data_files={key.strip("."): self.data_files[key] for key in self
    197 │   #         sample_by="document",
────────────────────────────────────────────────────────────────────────────────────────
TypeError: datasets.load.load_dataset() got multiple values for keyword argument
'num_proc'
注释掉'num_proc'此参数页无法解决
