### ISSUE TITLE
词汇多样性ModelScope Demo报错

### ISSUE THREAD

**Issue by Steven-Luo** [alibaba/data-juicer#34]
从https://modelscope.cn/studios/Data-Juicer/data_visulization_diversity/summary，这个页面的词汇多样性ModelScope链接点进去后，ModelScope页面报错：

ImportError: cannot import name 'prepare_diversity_model' from 'data_juicer.analysis.diversity_analysis' (/opt/conda/lib/python3.8/site-packages/data_juicer/analysis/diversity_analysis.py)
Traceback:
File "/opt/conda/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/home/studio_service/studio_file/PROJECT/app.py", line 9, in <module>
    from data_juicer.analysis.diversity_analysis import (DiversityAnalysis,

**Comment by zhijianma** [comment]
您好，感谢使用Data-Juicer！
猜测可能的原因是个别文件缺失导致，目前已经恢复。如果您已经下载并切安装完依赖，也可以在目录中 `<path-to-data-juicer>/demos/data_visualization_diversity` 中执行如下指令进行体验。
```python
streamlit run app.py
```
