### ISSUE TITLE
Auto-HPO是全流程自动化的还是需要人工介入

### ISSUE THREAD

**Issue by Steven-Luo** [alibaba/data-juicer#47]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

看了论文，发现里面有Auto-HPO的功能，似乎没有看到相关的代码，请问这个功能现在是全流程自动化的吗，还是说，通过调整yaml文件，生成不同的数据，然后用https://modelscope.cn/studios/Data-Juicer/auto_evaluation_helm/summary这个里面的评测，来观察结果，再调整数据生成策略，如此循环，亦或者是其他方法？

**Comment by yxdyc** [comment]
感谢关注~  全流程自动化的HPO代码（集成wandb Sweep）我们正在整理，最近就会有相关PR。    您所提到的“通过调整yaml，生成不同数据，......，如此循环，亦或者是其他方法” 是可行的，这个topic我们认为还有很大探索空间，目前不存在标准做法。也欢迎提供更多建议、尝试或作为data-juicer contributor直接贡献PR。

**Comment by Steven-Luo** [comment]
> 感谢关注~ 全流程自动化的HPO代码（集成wandb Sweep）我们正在整理，最近就会有相关PR。 您所提到的“通过调整yaml，生成不同数据，......，如此循环，亦或者是其他方法” 是可行的，这个topic我们认为还有很大探索空间，目前不存在标准做法。也欢迎提供更多建议、尝试或作为data-juicer contributor直接贡献PR。

好的，谢谢！
