### ISSUE TITLE
dedup across different dataset

### ISSUE THREAD

**Issue by breaddaerb** [alibaba/data-juicer#50]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

Hi, thanks for the great work. I'm wondering whether juicer apply dedup across different datasets when **reproducing redpajama**. For example, if there will be duplicates between [CommonCrawl-2023-06](https://modelscope.cn/datasets/Data-Juicer/redpajama-cc-2023-06-refined-by-data-juicer/summary) and [CommonCrawl-2022-05](https://modelscope.cn/datasets/Data-Juicer/redpajama-cc-2022-05-refined-by-data-juicer/summary)?

**Comment by HYLcool** [comment]
Hi, thanks for your interest!

We did not reproduce the CommonCrawl recipes of Redpajama. Those two datasets you posted above are actually from the refining recipes from Data-Juicer based on the Redpajama CommonCrawl datasets, and we did not apply deduplication across these 5 splits.

**Comment by breaddaerb** [comment]
Thanks!
