### ISSUE TITLE
export_path can not be a folder

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#66]
### Search before continuing 先搜索，再继续

- [X] I have searched the Data-Juicer issues and found no similar feature requests. 我已经搜索了 Data-Juicer 的 issue 列表但是没有发现类似的功能需求。

### Description 描述

- dataset_path是一个文件夹路径，里面多个json文件
- 处理完后，希望export_path也是一个文件夹，里面为对应多个json

### Are you willing to submit a PR for this feature? 您是否乐意为此功能提交一个 PR？

- [ ] Yes I'd like to help by submitting a PR! 是的！我愿意提供帮助并提交一个PR！

**Comment by HYLcool** [comment]
你好，感谢您的关注与使用~

这里想跟你明确下需求。比如这样一个情况：
- 处理前dataset_path为一个目录D，其中包括A.json，B.json，C.json三个文件
- 处理后，export_path可以支持写出到一个目录D'，其中也包括三个文件分别是A'.json，B'.json，C'.json，其中A'.json只会包括原来A.json的那些处理后的样本，B'.json和C'.json同理

这种处理方式符合你的期望吗？

**Comment by simplew2011** [comment]
> 你好，感谢你的关注与使用~
> 
> 这里想跟你明确下需求。比如这样一个情况：
> 
> * 处理前dataset_path为一个目录D，其中包括A.json，B.json，C.json三个文件
> * 处理后，export_path可以支持写出到一个目录D'，其中也包括三个文件分别是A'.json，B'.json，C'.json，其中A'.json只会包括原来A.json的那些处理后的样本，B'.json和C'.json同理
> 
> 这种处理方式符合你的期望吗？

期望是这样。

看了下hugging face dataset在加载一个文件夹内多个文件数据时，会组合成一个数据体，里面已经没法对应数据来自哪个文件内，在导出dataset.to_json()时可能真不能分别报错

**Comment by HYLcool** [comment]
嗯嗯是的，不干涉的话，datasets本身的确无法做到这个。此外，除了Deduplicator这些少部分算子需要有一个数据集的全局信息才可以进行外，大部分的Mapper和Filter实际上只是在样本级别进行处理，你把他们合并起来处理得到的结果其实与单个json文件分别去处理得到的结果是一致的。

因此，如果你的处理过程当中如果不涉及到去重的话，你可以用同一套config分别去处理多个json文件；如果需要全局去重的话，目前的一个可选方案是，在用data-juicer处理前，为每个json文件中的样本添加一个新的meta信息，指示其来自于哪一个json文件，等处理后再依靠这个meta信息恢复和分割出每个json文件的结果。你看是否可行？

**Comment by simplew2011** [comment]
看起来是可以的。

另外，

https://github.com/alibaba/data-juicer/blob/c938c1557824b2878db1a265da639913d1ad7e25/data_juicer/core/exporter.py#L212

- 在指定export_path为json后缀时，exporter内使用的是Exporter.to_jsonl方法，里面还是dataset.to_json()
- 最后导出后结果json文件是有问题的，每一行之间没有句号，以及最外面的中括号
- 看着还是按jsonlines格式导出了
- 这里可否加一个Exporter.to_json方法
- 
```
    @staticmethod
    def to_json(dataset, export_path, num_proc=1, **kwargs):
        """
        Export method for json/jsonl target files.

        :param dataset: the dataset to export.
        :param export_path: the path to store the exported dataset.
        :param num_proc: the number of processes used to export the dataset.
        :param kwargs: extra arguments.
        :return:
        """
        
        data_list = dataset.to_list()
        with open(export_path, 'w', encoding='utf-8') as f:
            json.dump(data_list, f, ensure_ascii=False, indent=4)
```

![image](https://github.com/alibaba/data-juicer/assets/66729924/be0acb58-1dc3-43bb-8f2e-15cd976d5b9e)

**Comment by HYLcool** [comment]
嗯，好的，我们之后会添加上json格式而不是jsonl格式的导出，不过就目前而言，你如果着急使用的话，可以直接在这一行的函数调用中添加一个参数`lines=False`

https://github.com/alibaba/data-juicer/blob/c938c1557824b2878db1a265da639913d1ad7e25/data_juicer/core/exporter.py#L188C13-L188C13

**Comment by HYLcool** [comment]
此外，我们也会认真考虑你最开始的那个建议。

目前初步来看，它可能和已有的一些Formatter相关的支持功能有隐含的冲突，我们需要一些时间去考虑如何集成这种保持原数据集目录结构的能力。但这可能不是一个短期的过程，如果之后能够实现这个需求，我们会第一时间告知你的~

再次感谢你的使用！❤️
