### ISSUE TITLE
token_num_filter的计算

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#89]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

https://github.com/alibaba/data-juicer/blob/main/data_juicer/ops/filter/token_num_filter.py#L49
基于[EleutherAI/pythia-6.9b-deduped](https://hf-mirror.com/EleutherAI/pythia-70m-deduped)
这个模型基于English，在token_num_filter对中文进行tokenize时，对token数量的统计是不是存在一些问题

![image](https://github.com/alibaba/data-juicer/assets/66729924/57806273-84c6-4a8d-8a4a-e79607352e3e)

**Comment by zhijianma** [comment]
您好，感谢您使用Data-Juicer！
在huggingface 中 [EleutherAI/pythia-6.9b)](https://huggingface.co/EleutherAI/pythia-6.9b)  中介绍到使用的为英语。如果您针对中文的 token 统计，可以选择 [通义千问7B](https://huggingface.co/Qwen/Qwen-7B) 或者 [百川2-7B](https://huggingface.co/baichuan-inc/Baichuan2-7B-Base) ， 这些 tokenizer 对中文词表进行了丰富的扩展。
