### ISSUE TITLE
31G的数据，运行去重的时候，保存数据的时候被kill

### ISSUE THREAD

**Issue by fuxuelinwudi** [alibaba/data-juicer#90]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

1111

### Additional 额外信息

1111111

**Comment by zhijianma** [comment]
您好，感谢您使用Data-Juicer！
建议提供详尽错误的日志信息或者截图，便于我们发现出现该现象的原因。
根据您的描述，我们建议您可以先检查并确认：
-  检查您的机器硬盘是否有富余的空间用于保存处理过的数据集
- 问题发生的准确位置，比如是在去重过程，还是导出数据过程

**Comment by fuxuelinwudi** [comment]
[4842680.894683] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=docker-9bb66ff24a5af61c7712662bb2905e00c6c9873e317396c1628b5164ebcbd285.scope,mems_allowed=0-1,oom_
memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod24ea3d2c_1bf6_425b_9f29_ec152b11f359.slice,task_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-bur
stable-pod24ea3d2c_1bf6_425b_9f29_ec152b11f359.slice/docker-9bb66ff24a5af61c7712662bb2905e00c6c9873e317396c1628b5164ebcbd285.scope,task=python,pid=26950,uid=0
[4842680.894944] Memory cgroup out of memory: Killed process 26950 (python) total-vm:153552968kB, anon-rss:62973884kB, file-rss:2488kB, shmem-rss:12kB, UID:0 pgtables:235072kB
oom_score_adj:969
[4842682.791669] oom_reaper: reaped process 26950 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:12kB

**Comment by fuxuelinwudi** [comment]
![image](https://github.com/alibaba/data-juicer/assets/73683264/bc44b65a-9c34-49ae-95b0-253f78f9db13)

**Comment by fuxuelinwudi** [comment]
我把 shard size 调到100，还是被kill，怎么解决这个问题呢？跑了很久，保存的时候就给我kill掉了

**Comment by zhijianma** [comment]
> 我把 shard size 调到100，还是被kill，怎么解决这个问题呢？跑了很久，保存的时候就给我kill掉了
shard size的值越小，保存的数据的分片就会越多。
第一次出现保存失败的时候，是否设置了shard size？  是否有限制docker 容器的 memory ?  可否调整一下shared memory size ?

**Comment by fuxuelinwudi** [comment]
第一次没有设置，不设置它默认写到一个文件里，我认为这样导致oom；然后我设置了shard size，设置了10 。100，但是结果都是oom，被kill掉。
我不是用的docker，就用的linux 命令来运行的；请问有什么办法解决吗？
我看shard size 设置了之后，就会被原始的文件分块来存储，但是现在分块了还是没办法保存下来。

**Comment by fuxuelinwudi** [comment]
**2023-11-21 03:45:30 | INFO     | data_juicer.core.exporter:122 - Split the dataset to export into 28440939 shards. Size of each shard <= 500.00 Bytes**

**Killed**

程序到这一行就没了

**Comment by HYLcool** [comment]
请问第一次没有设置shard size的时候是在哪一条日志后面报OOM的错的呢？

以及你的设备的总内存大概是多少呀？可以的话提供一下你的config配置文件，我们看下可能的原因

**Comment by fuxuelinwudi** [comment]
![image](https://github.com/alibaba/data-juicer/assets/73683264/9a1f3cd4-afd9-4219-b08f-0ed907284b0d)

这个是现在正在保存文件的时候的内存的变化。

第一次没设置shard size 的时候和设置了shard size 的时候的报 OOM 错的地方是一样的；

![image](https://github.com/alibaba/data-juicer/assets/73683264/6798fd6e-9507-4b86-a269-2529a2775347)
ji就这种最简单的处理过程

**Comment by fuxuelinwudi** [comment]
又被kill掉了，所以代码没到保存的时候，就是在 split 的时候就爆了

这一步就爆了
![image](https://github.com/alibaba/data-juicer/assets/73683264/5cbd3a61-bad6-4912-8356-c2d642cb8368)

**Comment by zhijianma** [comment]
麻烦在数据处理的环境内，执行一下如下的命令：
```shell
cat /sys/fs/cgroup/memory/memory.limit_in_bytes
```

**Comment by fuxuelinwudi** [comment]
68719476736

**Comment by fuxuelinwudi** [comment]
请问该如何设置

**Comment by zhijianma** [comment]
> 68719476736

换算的话约64G。如果您使用docker 容器，可以参考知乎 [docker如何动态修改资源](https://zhuanlan.zhihu.com/p/125627133)
```shell
docker update --cpus 24.0 -m 64g --memory-swap 64g docker_name
```

**Comment by fuxuelinwudi** [comment]
我不是用的 docker， 直接在服务器上命令行跑的，请问我怎么扩大这个 limit ？

**Comment by zhijianma** [comment]
> 我不是用的 docker， 直接在服务器上命令行跑的，请问我怎么扩大这个 limit ？

如果是云上机器的话，可以重新扩充资源。
