### ISSUE TITLE
[Bug]: alphanumeric_filter, char.isalnum()

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#98]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

pip

### Data-Juicer Version Data-Juicer版本

v0.1.2

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

https://github.com/alibaba/data-juicer/blob/main/data_juicer/ops/filter/alphanumeric_filter.py#L75
``````
            alnum_count = sum(
                map(lambda char: 1
                    if char.isalnum() else 0, sample[self.text_key]))
``````
Python3默认使用Unicode编码，所以`'汉字'.isalnum()`会返回True；encode()默认编码是UTF-8，编码成utf8之后，汉字就不会返回True了

``````
            alnum_count = sum(
                map(lambda char: 1
                    if char.encode().isalnum() else 0, sample[self.text_key]))
``````

### To Reproduce 如何复现

python tools/analyze_data.py --config configs/demo/analyser.yaml

### Configs 配置信息

``````
project_name: 'demo-analyser'
dataset_path: 'demos/data/demo-dataset.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset
text_keys: 'text'
export_path: './outputs/demo-analyser/demo-analyser-result.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
    - alphanumeric_filter:
``````

### Screenshots 截图

![image](https://github.com/alibaba/data-juicer/assets/66729924/7749d28c-02d5-457e-8380-41dd925531bc)

第五行全中文，alnum_ratio字母数字比例，正确应该是0

**Comment by drcege** [comment]
你好，我们遵循 Python 官方对于字母的定义。

详见：
https://docs.python.org/3/library/stdtypes.html#str.isalnum
https://docs.python.org/3/library/stdtypes.html#str.isalpha

比如，汉字 '**我**' 在 Unicode 数据库中的一般分类为 '**Lo**' ([Letter, other](https://www.unicode.org/versions/Unicode15.0.0/ch04.pdf))
```python
import unicodedata
print(unicodedata.category('我'))
```
凡是分类为 “Lm”, “Lt”, “Lu”, “Ll”, or “Lo” 的字符都被定义为“Letter”。
